platform :ios, ’10.0’  # 指定平台与版本
use_frameworks!

target 'hello-world' do
pod 'SnapKit', '~> 4.0.0'
pod 'Alamofire', '~> 4.5'
pod 'Kingfisher', '~> 4.0'
pod 'IBAnimatable’, '~> 5.0.0'
# Toast扩展包
pod 'Toast-Swift', '~> 3.0.1'
pod 'SwiftyJSON'
pod 'SwifterSwift'
pod 'SVProgressHUD'

end
